name: HyperOS Porting

on:
  workflow_dispatch:
    inputs:
      base_rom_url:
        description: 'Base ROM Link (.zip)'
        required: true
      port_rom_url:
        description: 'Port ROM Link (.zip)'
        required: true
      fs_type:
        description: 'Filesystem Type'
        required: true
        type: choice
        options:
          - erofs
          - ext4
        default: 'erofs'
      pack_type:
        description: 'Output Format'
        required: true
        type: choice
        options:
          - super
          - payload
        default: 'super'
      extra_args:
        description: 'Extra CLI flags (e.g., --ksu)'
        required: false

jobs:
  port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Disk Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 12288
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 p7zip-full brotli android-sdk-libsparse-utils python3-pip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Download Stock ROM
        run: |
          aria2c -x 16 -s 16 -o base.zip "${{ github.event.inputs.base_rom_url }}"

      - name: Download Port ROM
        run : |
          aria2c -x 16 -s 16 -o port.zip "${{ github.event.inputs.port_rom_url }}"

      - name: Run Porting Script
        run: |
          sudo python3 main.py \
            --stock base.zip \
            --port port.zip \
            --fs-type ${{ github.event.inputs.fs_type }} \
            --pack-type ${{ github.event.inputs.pack_type }} \
            ${{ github.event.inputs.extra_args }}

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: HyperOS-Port-${{ github.event.inputs.pack_type }}
          path: out/*.zip
